### PR TITLE
feat - added avatar and common component css

### PR DESCRIPTION
**Pull request by ashishnnnnn**
I have added avatar and a component.css which will be common for all other components including avatar

### CODE REVIEW

**Comment by ashishnnnnn** [comment]
Sorry ... I forgot to add those images file..but you can assume there are some image

**Comment by lannisterrr** [comment]
looks good you can merge it.

**Review by ArjunGTX — APPROVED** [review]
Looks good. Just one suggestion, avoid deep nesting of selectors

**Comment by ashishnnnnn** [comment]
Okay..will try to reduce that.. most of them are utility class of padding ,margin and font size

**Pull request merged**
